version: '3.7'

services:
  email-module:
    build: .
    volumes:
      - ./:/app
    container_name: 'email-module'
    ports:
      - 32801:8080
  mysql:
    image: mysql:5.6
    container_name: 'mysql-email-module'
    ports:
      - 32800:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: email_module
